project:
  type: website

website:
  title: "My R Website"
  navbar:
    left:
      - href: Project_Proprosal.qmd
        text: Social Media USage Analysis
      - href: index.qmd
        text: Home
      - href: Dataset.qmd
        text: Dataset
      - href: AnalysisPlan.qmd
        text: Analysis Plan
      - href: InitialDataAnalysis.qmd
        text: IDA

      # - href: results.qmd
      #   text: Results

format:
  html:
    theme: cosmo
    toc: true
    code-copy: true

execute:
  echo: true
  warning: false
  message: false

# - href: index.qmd
#   text: Home
# - href: Dataset.qmd
#   text: Dataset
# - href: AnalysisPlan.qmd
#   text: Analysis Plan
# - href: InitialDataAnalysis.qmd
#   text: IDA